local cjson = require("cjson")
local base64 = require("base64")
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 55haitao.
--- DateTime: 2023/7/19 13:12
---

local log = 'eyJhY3Rpb24iOiJicm93c2luZyIsImFwcCI6ImRlZmF1bHRfYXBwIiwiYXBwVmVyc2lvbiI6ImRlZmF1bHRfYXBwX3ZlcnNpb24iLCJ1c2VySUQiOiJkZWZhdWx0X3VzZXJfaWQiLCJkZXZpY2VJRCI6ImRlZmF1bHRfZGV2aWNlX2lkIiwiZGV2aWNlVHlwZSI6ImRlZmF1bHRfZGV2aWNlX3R5cGUiLCJvcGVyYXRpbmdTeXN0ZW0iOiJkZWZhdWx0X29wZXJhdGluZ19zeXN0ZW0iLCJvcGVyYXRpbmdTeXN0ZW1WZXJzaW9uIjoiZGVmYXVsdF9vc192ZXJzaW9uIiwiYnJvd3NlckluZm8iOiJkZWZhdWx0X2Jyb3dzZXJfaW5mbyIsInNjcmVlblJlc29sdXRpb24iOiJkZWZhdWx0X3NjcmVlbl9yZXNvbHV0aW9uIiwic2NyZWVuV2lkdGgiOiJkZWZhdWx0X3NjcmVlbl93aWR0aCIsInNjcmVlbkhlaWdodCI6ImRlZmF1bHRfc2NyZWVuX2hlaWdodCIsImRldmljZU1hbnVmYWN0dXJlciI6ImRlZmF1bHRfZGV2aWNlX21hbnVmYWN0dXJlciIsImxhbmd1YWdlIjoiZGVmYXVsdF9sYW5ndWFnZSIsIklQQWRkcmVzcyI6ImRlZmF1bHRfaXBfYWRkcmVzcyIsIm5ldHdvcmtPcGVyYXRvciI6ImRlZmF1bHRfbmV0d29ya19vcGVyYXRvciIsIm5ldHdvcmtDb25uZWN0aW9uVHlwZSI6ImRlZmF1bHRfbmV0d29ya19jb25uZWN0aW9uX3R5cGUiLCJsb2NhdGlvbiI6ImRlZmF1bHRfbG9jYXRpb24iLCJsb25naXR1ZGUiOiJkZWZhdWx0X2xvbmdpdHVkZSIsImxhdGl0dWRlIjoiZGVmYXVsdF9sYXRpdHVkZSIsInJlc291cmNlSWQiOiJkZWZhdWx0X3Jlc291cmNlX2lkIiwicmVzb3VyY2VUeXBlIjoiZGVmYXVsdF9yZXNvdXJjZV90eXBlIiwicmVzb3VyY2VMb2NhdGlvbiI6ImRlZmF1bHRfcmVzb3VyY2VfbG9jYXRpb24iLCJicm93c2luZ1RpbWUiOiJkZWZhdWx0X2Jyb3dzaW5nX3RpbWUifQ=='

local logTable = {}
if log then
    logTable = cjson.decode(base64.decode(log))
end

local params = '{"name": "John", "age": 30, "city": "New York"}'

local queryStr = params .. '&utrace=' .. 'ogenes'
if logTable then
    print(#logTable)
    for k,v in pairs(logTable) do
        queryStr = queryStr .. '&' .. k .. '=' .. v
    end
end
print(queryStr);
--ngx.location.capture('/user_behavior_click?' .. params .. '&utrace=' .. uid .. '&un_log=' .. un_log)

